version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: svg-sprite-loader
    versions:
    - 5.2.1
    - 6.0.0
    - 6.0.2
    - 6.0.5
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: copy-webpack-plugin
    versions:
    - 5.1.2
    - 7.0.0
    - 8.0.0
    - 8.1.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: karma-webpack
    versions:
    - 4.0.2
