#!/bin/sh

# For SourceTree app finding Node easily
export PATH=/usr/local/bin:$PATH

STAGED_FILES=$(git diff --cached --name-only | grep -E '(.js)$')
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

if [[ ! -x "$ESLINT" ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m (npm i --save --save-exact --dev eslint)"
  exit 1
fi

PASS=true

echo "\nValidating Javascript:\n"

for FILE in $STAGED_FILES
do
  "$ESLINT" -c .eslintrc.json "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[32mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
